### ISSUE TITLE
Lazy initialization of databases from configuration.yaml

### ISSUE THREAD

**Issue by maciejgrzybek** [prestodb/tempto#142]
When there are no tests scheduled for execution using database  configured in yaml configuration, the database should not be connected.
E.g.:
tempto yaml:
```yaml
databases:
  default:
    alias: presto

  hive:
    host: hadoop-master

  mysql:
    jdbc_driver_class: com.mysql.jdbc.Driver
    jdbc_url: jdbc:mysql://mysql:3306/test
    jdbc_user: root
```

running only Hive tests (e.g. `TestAllDatatypesFromHiveConnector.java`) MySQL instance shouldn't be expected to run.
